version: "3"
services:
    asr_system:
        build:
            context: .
            dockerfile: docker/asr_system/Dockerfile
        image: kinouchi1000/espnet_asr_server
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        ports:
            - "5000:5000"
        command: "python run_asr_server.py"
        volumes:
            - ./src:/app
