version: "2.4"
services:
    asr_system:
        build:
            context: .
            dockerfile: docker/asr_system/Dockerfile
        image: kinouchi1000/espnet_asr_server
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        ports:
            - "5000:5000"
        command: "python src/run_asr_server.py"
        # tty: true
        volumes:
            - ./src:/app/src
            - ./test:/app/test
            - ./docker/data/split_wav:/media/split_wav
            - ./docker/data/text:/mnt/text
            - ./docker/data/models:/mnt/models
